// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWX-Xv0fo4EWDiLxIPdbK0URpiVVyagww',
    appId: '1:545971873958:web:7fcbab6a37af26b4b86c67',
    messagingSenderId: '545971873958',
    projectId: 'agropal-532e9',
    authDomain: 'agropal-532e9.firebaseapp.com',
    storageBucket: 'agropal-532e9.appspot.com',
    measurementId: 'G-YVW9B9E5RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOg4Sgj1slzFlofjUKJR3MJY4OeXxPraY',
    appId: '1:545971873958:android:45916242b3624270b86c67',
    messagingSenderId: '545971873958',
    projectId: 'agropal-532e9',
    storageBucket: 'agropal-532e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5dk46VlvzGn0a0Ux9okBhlQ4aqqJcws',
    appId: '1:545971873958:ios:f061d4bb7ce0d6ecb86c67',
    messagingSenderId: '545971873958',
    projectId: 'agropal-532e9',
    storageBucket: 'agropal-532e9.appspot.com',
    iosClientId:
        '545971873958-s4ncb1dlj5gv901feb54smuohva2bu85.apps.googleusercontent.com',
    iosBundleId: 'com.sanushradalage.agropal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5dk46VlvzGn0a0Ux9okBhlQ4aqqJcws',
    appId: '1:545971873958:ios:f061d4bb7ce0d6ecb86c67',
    messagingSenderId: '545971873958',
    projectId: 'agropal-532e9',
    storageBucket: 'agropal-532e9.appspot.com',
    iosClientId:
        '545971873958-s4ncb1dlj5gv901feb54smuohva2bu85.apps.googleusercontent.com',
    iosBundleId: 'com.sanushradalage.agropal',
  );
}
